### ISSUE TITLE
Remove 'class' metric

### ISSUE THREAD

**Issue by jolkdarr** [racodond/sonar-json-plugin#31]
Hi

I use the plugin in some Java projects for which I just wish line accounting and rule checking for JSON files.
Please, could you add a Sonarqube parameter to enable/disable JSON class accounting?

Regards.

**Comment by racodond** [comment]
Hi @jolkdarr,

Thanks for your feedback!
I will remove this 'class' metric from the JSON plugin because it doesn't really make sense.
David
