### ISSUE TITLE
New rule: Duplicated blocks

### ISSUE THREAD

**Issue by jolkdarr** [racodond/sonar-json-plugin#34]
Hello

Like Java plugin, sonar-json-plugin should provide a rule to check duplications in JSON files.

**Comment by racodond** [comment]
Hi @jolkdarr,

It doesn't really make sense to me to check for duplicated pieces of code in JSON "data" files.
Do you have real life examples of JSON files in which you would have liked to get this piece of information?

Thanks!

David

**Comment by jolkdarr** [comment]
Hi David

I am currently working in a project containing 4000 lines in JSON files. The numbers of files and total lines will grow at each release. Many JSON files contain definitions set with key/value pairs that potentially may be duplicated. I suggest the rule anticipating such issues although they don't occur so far.

**Comment by racodond** [comment]
Hello,

So, it's not really about detection of duplicated blocks of code that you're after, right?

You would like a rule that checks:
- If a key appears twice or more in the same object?
- If a key appears twice or more with the same value in the same object?
```
{
  "abc": "blabla...,
  "def" : "zzz",
  "def" : "aaa",
}
```

**Comment by jolkdarr** [comment]
Hello David

I was rather suspecting common groups of key/value pairs in two or more JSON files.
To "fix" the issue, I may need to create a new JSON file with shared keys/values (and update accordingly the parsing code of course)

**Comment by racodond** [comment]
@jolkdarr: I'm not really convinced by detection of duplicated blocks... And I wouldn't really know what threshold to set.
