### ISSUE TITLE
Improve handling of source file encoding (UTF-8 BOM)

### ISSUE THREAD

**Issue by Bertk** [racodond/sonar-json-plugin#35]
We have some JSON files using UTF-8 with BOM. The JSON plug-in V2.2 cannot read the source file and creates the following error message.
```
2018-09-24T15:01:11.4826448Z ##[error]ERROR: Unable to parse file: C:/w/7/s/src/App/appInfo.json
2018-09-24T15:01:11.4827433Z ERROR: Unable to parse file: C:/w/7/s/src/App/appInfo.json
2018-09-24T15:01:11.4834948Z ##[error]ERROR: Parse error at line 1 column 1:
1: {
^
```
Other SonarQube plug-ins handle UTF-8 with BOM files correctly.

**Comment by racodond** [comment]
Hi @Bertk,

BOM is supposed to be supported. See https://github.com/racodond/sonar-json-plugin/blob/master/json-frontend/src/main/java/org/sonar/json/parser/JSONGrammar.java#L40

What encoding did you set for the SonarQube analysis? UTF-8?
If so, could you please re-analyze this file and send it to me as well as the full log of the analysis?

Thank you

David

**Comment by Bertk** [comment]
Hi David, 
I created a unit test which checks the appInfo.json with UTF-8 BOM file encoding and the plug-in is able to read it.
I checked the scanner context on the server for this analysis and this shows the setting `sonar.sourceEncoding=utf-8` for the projects of the VS solution. This configuration seams to be a MSBuild scanner default setting.

I close this issue.

Best regards
Bert
